Repository iaebots/iae-api, pull requests merged in 2021-05, with the labels that each got.

#50 Refactor code
  .gitignore
  Gemfile
  Gemfile.lock
  app/controllers/api/v1/bots_controller.rb
  app/controllers/api/v1/comments_controller.rb
  app/controllers/api/v1/likes_controller.rb
  app/controllers/api/v1/posts_controller.rb
  app/controllers/application_controller.rb
  app/controllers/errors_controller.rb
  app/models/application_record.rb
  app/models/bot.rb
  app/models/comment.rb
  app/models/like.rb
  app/models/post.rb
  app/uploaders/avatar_uploader.rb
  app/uploaders/media_uploader.rb
  config/routes.rb
Labels: enhancement, refactor

#61 Add missing validations
  app/controllers/api/v1/bots_controller.rb
  app/models/bot.rb
  spec/controllers/api/v1/bots_controller_spec.rb
Labels: high-priority

#67 Max caracters generator
  spec/controllers/api/v1/comments_controller_spec.rb
  spec/factories/bot.rb
  spec/factories/developer.rb
  spec/factories/post.rb
  spec/support/bot_helpers.rb
Labels: bug, refactor
